### ISSUE TITLE
Error when searching simple XML file

### ISSUE THREAD

**Issue by madis** [actionshrimp/vim-xpath#14]
xml-xpath would be very useful plugin. Unfortunately I'm getting an error that makes vim pretty much unusable after querying simple XML file (have to close all files to get rid of the error). 

I installed the plugin and tried to perform a search: `:XPathSearchPrompt "Selector/Numbers"`

XML file:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<File xmlns="Megaworld">
  <Base>
    <Selector>
      <JustAString>Hello</JustAString>
      <ASingleElement>true</ASingleElement>
      <Numbers>12</Numbers>
    </Selector>
    <Selector>
      <ASingleElement>false</ASingleElement>
      <Numbers>34</Numbers>
      <Nested>
        <Thing>a nested thing</Thing>
      </Nested>
      <NestedArray>
        <Thing>first</Thing>
        <Thing>second</Thing>
      </NestedArray>
    </Selector>
  </Base>
</File>
```

And got the following error:
```
Error detected while processing function <SNR>95_XPathChanged[8]..XPathEvaluate[3]..provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/madisnoemme/.config/nvim/plugged/vim-xpath/python/vim_adaptor.py", line 30, in evaluate_xpath
    xml = get_buffer_string(bufnr)
  File "/Users/madisnoemme/.config/nvim/plugged/vim-xpath/python/vim_adaptor.py", line 18, in get_buffer_string
    vim.buffers[0]
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 373, in __getitem__
    raise KeyError(number)
```

**Comment by actionshrimp** [comment]
Hey madis,

Looks like you're using neovim from the stack trace? I haven't tried getting this to work on neovim yet but it looks like the buffer numbering system might be different from the vim versions I've tested the plugin on (suggested by issues like this one https://github.com/neovim/neovim/issues/2823 even though that appears to be fixed)? vim itself changed the buffer numbering system too recently so it might be something to do with that.

What version of neovim are you using? I'll install that and see if I can make a patch to get this to work in the different vim versions, as well as neovim.

**Comment by actionshrimp** [comment]
Hey madis, pushed a fix for that. If you update the plugin on master it should hopefully solve your issue.

BTW - the XML file you're using has a default namespace at the top, so you'll want your xpath search to be something like `//default:Selector/default:Numbers`. Might be worth giving the namespaces section of this https://github.com/actionshrimp/vim-xpath/blob/master/doc/xpath.txt a read, as the plugin assumes some default prefixes etc.

Also `:XPathSearchPrompt` is a command you run with no arguments to enter an interactive search mode- not sure if it works as you'd expect if you pass it a string directly, possibly one for another patch if there's a valid use case for that.

Hope this helps.

**Comment by madis** [comment]
Thank you for so quick reply :)
I'm using neovim `NVIM v0.1.6-286-gfdc48ca Build type: Dev`

The update fixed the issue I was having. 

Having to specify namespaces for every node is little bit cumbersome. It would be nice if I could set a flag so that the plugin uses the first namespace it finds. Most of my files have none or one.

Thank you again for the support. Code mode!
