### ISSUE TITLE
Python3 support.

### ISSUE THREAD

**Issue by hovissimo** [actionshrimp/vim-xpath#16]
At a minimum, the feature is hard-coded to exit if +python is missing without even checking for +python3.

**Comment by JonnyRa** [comment]
This stops it working with vim 8

**Comment by JonnyRa** [comment]
I asked a question on vim stack exchange https://vi.stackexchange.com/questions/14135/how-to-write-a-plugin-that-works-for-both-python3-and-python about how to do this.

I tried replacing  the py and pyfile calls with pyx and pyxfile calls but I hit a dead end.

I believe I also had to install the relevant xml library for python3 (can't remember the details)

It was failing when some results were coming back and I couldn't make sense of the errors.  They were vimscript ones as opposed to python ones, I had a bit of a poke around but didn't get anywhere as the code didn't include the words py or pyfile!

Have removed the plugin now and just been using `xmllint --xpath` instead but hopefully this information might be useful to someone else.

**Comment by actionshrimp** [comment]
Thanks for taking a look JonnyRa - sorry, I don't really use the plugin or Vim8 myself at the minute and haven't had a lot of time to look into this but I'll update on here to let you know if I get a chance to fix it. Similarly I'm more than happy to accept PRs if anyone fancies giving it a go.

**Comment by actionshrimp** [comment]
Addressed by #17, thanks @FlorianMickler!
