### ISSUE TITLE
Use Vim's autoload mechanism to lazily load the plugin

### ISSUE THREAD

**Issue by blueyed** [actionshrimp/vim-xpath#7]
The vim-xpath plugin loads the python module during startup via `plugin/vim-xpath.vim`.

It would be nice, if this expensive action would get done via Vim's autoload mechanism, only when the plugin is invoked for the first time.

Let me know if you could need more information about how to do this.

**Comment by actionshrimp** [comment]
Not sure what this involves so closing this for now. Let me know if you have any pointers towards it.

**Comment by blueyed** [comment]
@actionshrimp 
Sorry for not responding earlier.
It would involve moving the expensive functions, e.g. loading the Python module, into a function.

While at it, it is a good practice to only do setup-stuff in "plugin" (e.g. defining mappings, autocommands etc), but have the real functions in "autoload" then.

**Comment by actionshrimp** [comment]
Ah I see what you mean, I'll take a look.

**Comment by actionshrimp** [comment]
This is done as part of 230675b - only the commands are preloaded now, and everything else is loaded at first invocation. Thanks for pointing this out :)

**Comment by blueyed** [comment]
Thanks! :)
